# Generated by Django 3.1.4 on 2020-12-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0002_apache_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
