# Generated by Django 3.1.4 on 2020-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0003_auto_20201205_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='ip',
            name='address',
            field=models.CharField(max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='countryname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='hostname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='org',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='region',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='timezone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
