# Generated by Django 3.1.4 on 2020-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0004_auto_20201205_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='longitude',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
