# Generated by Django 3.1.4 on 2020-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0006_auto_20201205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='timezone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
