# Generated by Django 3.1.4 on 2020-12-18 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0008_log_line_server_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='apache_log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
