# Generated by Django 3.1.4 on 2021-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0009_apache_log_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='apache_log',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
