# Generated by Django 2.2.5 on 2021-01-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
