# Generated by Django 2.2.5 on 2021-01-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0014_auto_20210110_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security',
            field=models.CharField(choices=[('CF', 'Confidental'), ('S', 'Secret'), ('TS', 'Top Secret')], default='CF', max_length=2),
        ),
    ]
