# Generated by Django 2.2.5 on 2021-01-10 18:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0015_userprofile_security'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default='385', max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security',
            field=models.CharField(choices=[('CF', 'Confidental'), ('S', 'Secret'), ('TS', 'Top Secret')], max_length=2),
        ),
    ]
