# Generated by Django 2.2.5 on 2021-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0018_auto_20210110_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='security',
            field=models.CharField(choices=[('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top_Secret', 'Top_Secret')], max_length=12),
        ),
    ]
