# Generated by Django 3.1.4 on 2021-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0018_auto_20210110_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='security',
            field=models.CharField(choices=[('CF', 'Confidential'), ('S', 'Secret'), ('TS', 'Top Secret')], max_length=2),
        ),
    ]
