# Generated by Django 3.1.4 on 2021-01-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0018_auto_20210110_1909'),
        ('cti', '0010_apache_log_analyzed'),
    ]

    operations = [
    ]
