# Generated by Django 3.1.4 on 2021-01-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0019_auto_20210115_1452'),
        ('cti', '0019_merge_20210115_1724'),
        ('cti', '0019_auto_20210115_1225'),
    ]

    operations = [
    ]
